
services:
  st-container:
    container_name: st-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
